version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
  python_euroleague:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - app-tier
    command:
      python main.py

networks:
  app-tier:
    driver: bridge
