version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb:/home/volumes/mongodb
    networks:
      - app-tier
  python_euroleague:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - app-tier
    command:
      python main.py

  euroleague-api:
    build:
      context: ../euroleague-dashboard-api
      dockerfile: ./Dockerfile
    depends_on:
      - python_euroleague
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8989
      --reload
      "
    networks:
      - app-tier
    ports:
      - "8989:8989"
networks:
  app-tier:
    driver: bridge

volumes:
  mongodb:
